---
title: "Testing experiments"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Testing experiments}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(SplineHazardRegression)
## simulation parameters
   knots = c(0, 1, 3, 6, 10, NA, NA)
   betac = 1 * c(0.05, 0.05, 0.05, 0.05, 0.40, 0.1, 0.05)
   HParm = data.frame(knots, betac) # 'A Simple B-Spline'ta
   cll = c(0, 5)
   cup = c(5, 10)
   cih = c(0.0125, 0.025)
   CParm = data.frame(cll, cup, cih) # 'Light Censoring'
## CONTROL THE SIMULATION SEED FOR REPRODUCIBILITY
  eff_seed <- sample(1:2^15, 1)
  print(sprintf("Seed for session: %s", eff_seed))
  set.seed(eff_seed)
  set.seed( 32427 ) #this one poses convergence issues
  
  ##TO TEST
  # help( "constrOptim", package = "stats")
  # help( "bobyqa", package = "minqa") #stat.ucla.edu
  # help( "bobyqa", package = "nloptr") #much heavier package
  ##MANY MORE AT https://cran.r-project.org/web/views/Optimization.html
  
## calculate simulation true hazard and censoring distributions
   INPUTS = etsim_inputs( HParam=HParm, CParam=CParm, SampleSize = 301 )
## simulate time-to-event data using true distribution
   SimDat = etsim(INPUTS)
## Solve ...
   timeout = seq( 0, 10, length.out = 101 )
   # First, we calculate the best knots
   Result = hspcore(yd=SimDat, ORDER=4, Exterior.knots = c(0,10), Interior.knots=NULL, SelectBestKnots = TRUE, time=timeout, Bootstrap = 0, verbose=TRUE )
   Interior.knots = Result$Interior.knots
   Interior.knots
   # Then, we apply bootstrap to calculate the variance
   Result = hspcore(yd=SimDat, ORDER=4, Exterior.knots = c(0,10), Interior.knots=Interior.knots, SelectBestKnots = FALSE, time=timeout, Bootstrap = 200, verbose=FALSE )
     # Convergence issues with some algorithms
   print( paste0( "Times converged: L-BFGS-B ", sum( Result$convergence[,1]==0 ), ", PORT ", sum( Result$convergence[,2]==0 ),
                  ", Barrier ", sum( Result$convergence[,3]==0 ), ", BOBYQA ", sum( Result$convergence[,4]>0 ) ) )
    # which method found the minimum objective?
   table( c("L-BFGS-B","PORT", "Barrier", "BOBYQA", "None")[ Result$convergenceb[,5] ] )
    # were the bootstrap iterations having all coefficients non-zero? (i.e. how many of the basis B-splines with the selected knots were used?)
   table( rowSums( Result$alphab > 1.E-6 ) ) #in most cases, 8 or 9 coefs out of 10 were non-zero
   colSums( Result$alphab > 1.E-6 ) # the extreme basis functions were the less used
```

Let's visualize the results.

```{r, result-figures-side, fig.show="hold", out.width="50%", echo=FALSE}
### COMBINED FIGURES
plot( INPUTS$t, INPUTS$h, type="l", col="green",ylim=c(0,1.0),xlab="t",ylab="event hazard rate",bty="n")
lines( Result$t, Result$h[,1], col="blue")
lines( Result$t, Result$h[,2], lty="dashed", col="blue" )
lines( Result$t, Result$h[,3], lty="dashed", col="blue" )
# lines( Result2$t, Result2$h[,1], col="red")
# lines( Result2$t, Result2$h[,2], lty="dashed", col="red" )
# lines( Result2$t, Result2$h[,3], lty="dashed", col="red" )
abline(v=c(0,5,10), h=seq(0.0,1.0,0.2), lty=2,col="gray" )

Boundary.knots = c(0,10)
DELTA = (Boundary.knots[2]-Boundary.knots[1])/(length(INPUTS$t)-1)
H.true = cumsum(INPUTS$h*DELTA)
 DT = c(0, Result$t[-1]-Result$t[-length(Result$t)] ) 
H.result  = cumsum( Result$h[,1] * DT )

plot( INPUTS$t, H.true, type="l", col="green",ylim=c(0,max(cumsum( Result$h[,3] * DT ))), xlab="t",ylab="Cumulative Hazard",bty="n")
lines( Result$t, H.result, col="blue")
lines( Result$t, cumsum( Result$h[,2] * DT ), lty="dashed", col="blue")
lines( Result$t, cumsum( Result$h[,3] * DT ), lty="dashed", col="blue")
# lines( Result2$t, H.result2, col="red")
# lines( Result2$t, cumsum( Result2$h[,2] * DT ), lty="dashed", col="red")
# lines( Result2$t, cumsum( Result2$h[,3] * DT ), lty="dashed", col="red")
abline(v=c(0,5,10), h=seq(0.0,2.5,0.5), lty=2,col="gray" )

plot( INPUTS$t, INPUTS$Sh, type="l", col="green", ylim=c(0,1.0),xlab="t",ylab= "Survival Probability [exp(-H)]",bty="n")
lines( Result$t, exp( - H.result ), col="blue")
lines( Result$t, exp( - cumsum( Result$h[,2] * DT ) ), lty="dashed", col="blue")
lines( Result$t, exp( - cumsum( Result$h[,3] * DT ) ), lty="dashed", col="blue")
# lines( Result2$t, exp( - H.result2 ), col="red")
# lines( Result2$t, exp( - cumsum( Result2$h[,2] * DT ) ), lty="dashed", col="red")
# lines( Result2$t, exp( - cumsum( Result2$h[,3] * DT ) ), lty="dashed", col="red")
abline(v=c(0,5,10), h=seq(0.0,1.0,0.2), lty=2,col="gray" )

plot( INPUTS$t, INPUTS$Sh, type="l", col="green", ylim=c(0,1.0),xlab="t",ylab="Bootstrap Survival Probability",bty="n")
lines( Result$t, Result$S[,1], col="blue")
lines( Result$t, Result$S[,2], lty="dashed", col="blue")
lines( Result$t, Result$S[,3], lty="dashed", col="blue")
# lines( Result2$t, Result2$S[,1], col="red")
# lines( Result2$t, Result2$S[,2], lty="dashed", col="red")
# lines( Result2$t, Result2$S[,3], lty="dashed", col="red")
abline(v=c(0,5,10), h=seq(0.0,1.0,0.2), lty=2,col="gray" )
```

## What if using quadatric splines instead?

```{r }
## Solve ...
   timeout = seq( 0, 10, length.out = 101 )
   # First, we calculate the best knots
   Result = hspcore(yd=SimDat, ORDER=3, Exterior.knots = c(0,10), Interior.knots=NULL, SelectBestKnots = TRUE, time=timeout, Bootstrap = 0, verbose=TRUE )
   Interior.knots = Result$Interior.knots
   Interior.knots
   # Then, we apply bootstrap to calculate the variance
   Result = hspcore(yd=SimDat, ORDER=3, Exterior.knots = c(0,10), Interior.knots=Interior.knots, SelectBestKnots = FALSE, time=timeout, Bootstrap = 200, verbose=FALSE )
     # Convergence issues with some algorithms
   print( paste0( "Times converged: L-BFGS-B ", sum( Result$convergence[,1]==0 ), ", PORT ", sum( Result$convergence[,2]==0 ),
                  ", Barrier ", sum( Result$convergence[,3]==0 ), ", BOBYQA ", sum( Result$convergence[,4]>0 ) ) )
    # which method found the minimum objective?
   table( c("L-BFGS-B","PORT", "Barrier", "BOBYQA", "None")[ Result$convergenceb[,5] ] )
    # were the bootstrap iterations having all coefficients non-zero? (i.e. how many of the basis B-splines with the selected knots were used?)
   table( rowSums( Result$alphab > 1.E-6 ) ) #in most cases, 4 coefs were non-zero
   colSums( Result$alphab > 1.E-6 ) # the extreme endpoint basis function was the less used
```

```{r, resultQ-figures-side, fig.show="hold", out.width="50%", echo=FALSE}
### COMBINED FIGURES
plot( INPUTS$t, INPUTS$h, type="l", col="green",ylim=c(0,1.0),xlab="t",ylab="event hazard rate",bty="n")
lines( Result$t, Result$h[,1], col="blue")
lines( Result$t, Result$h[,2], lty="dashed", col="blue" )
lines( Result$t, Result$h[,3], lty="dashed", col="blue" )
# lines( Result2$t, Result2$h[,1], col="red")
# lines( Result2$t, Result2$h[,2], lty="dashed", col="red" )
# lines( Result2$t, Result2$h[,3], lty="dashed", col="red" )
abline(v=c(0,5,10), h=seq(0.0,1.0,0.2), lty=2,col="gray" )

Boundary.knots = c(0,10)
DELTA = (Boundary.knots[2]-Boundary.knots[1])/(length(INPUTS$t)-1)
H.true = cumsum(INPUTS$h*DELTA)
 DT = c(0, Result$t[-1]-Result$t[-length(Result$t)] ) 
H.result  = cumsum( Result$h[,1] * DT )

plot( INPUTS$t, H.true, type="l", col="green",ylim=c(0,max(cumsum( Result$h[,3] * DT ))), xlab="t",ylab="Cumulative Hazard",bty="n")
lines( Result$t, H.result, col="blue")
lines( Result$t, cumsum( Result$h[,2] * DT ), lty="dashed", col="blue")
lines( Result$t, cumsum( Result$h[,3] * DT ), lty="dashed", col="blue")
# lines( Result2$t, H.result2, col="red")
# lines( Result2$t, cumsum( Result2$h[,2] * DT ), lty="dashed", col="red")
# lines( Result2$t, cumsum( Result2$h[,3] * DT ), lty="dashed", col="red")
abline(v=c(0,5,10), h=seq(0.0,2.5,0.5), lty=2,col="gray" )

plot( INPUTS$t, INPUTS$Sh, type="l", col="green", ylim=c(0,1.0),xlab="t",ylab= "Survival Probability [exp(-H)]",bty="n")
lines( Result$t, exp( - H.result ), col="blue")
lines( Result$t, exp( - cumsum( Result$h[,2] * DT ) ), lty="dashed", col="blue")
lines( Result$t, exp( - cumsum( Result$h[,3] * DT ) ), lty="dashed", col="blue")
# lines( Result2$t, exp( - H.result2 ), col="red")
# lines( Result2$t, exp( - cumsum( Result2$h[,2] * DT ) ), lty="dashed", col="red")
# lines( Result2$t, exp( - cumsum( Result2$h[,3] * DT ) ), lty="dashed", col="red")
abline(v=c(0,5,10), h=seq(0.0,1.0,0.2), lty=2,col="gray" )

plot( INPUTS$t, INPUTS$Sh, type="l", col="green", ylim=c(0,1.0),xlab="t",ylab="Bootstrap Survival Probability",bty="n")
lines( Result$t, Result$S[,1], col="blue")
lines( Result$t, Result$S[,2], lty="dashed", col="blue")
lines( Result$t, Result$S[,3], lty="dashed", col="blue")
# lines( Result2$t, Result2$S[,1], col="red")
# lines( Result2$t, Result2$S[,2], lty="dashed", col="red")
# lines( Result2$t, Result2$S[,3], lty="dashed", col="red")
abline(v=c(0,5,10), h=seq(0.0,1.0,0.2), lty=2,col="gray" )
```
